VALID_TOOLCHAINS := pnacl

ifeq (,$(wildcard $(NACL_SDK_ROOT)/tools/oshelpers.py))
$(error NACL_SDK_ROOT is set to an invalid location: $(NACL_SDK_ROOT))
endif

TARGET = graphviz

include $(NACL_SDK_ROOT)/tools/common.mk

LIBS = ppapi pthread

CFLAGS = -Wall -std=c99
SOURCES = lib/graphviz.c

# Build rules generated by macros from common.mk:
$(foreach src,$(SOURCES),$(eval $(call COMPILE_RULE,$(src),$(CFLAGS))))

$(eval $(call LIB_RULE,$(TARGET),$(SOURCES)))
