name: graphviz
description: GraphViz NaCl module and polymer.dart component
dependencies:
  browser: any
  logging: '>=0.9.2 <0.10.0'
  polymer: '>=0.15.5 <0.16.0'
dev_dependencies:
  unittest: '>=0.11.0+3 <0.12.0'
transformers:
- $dart2js:
    commandLineOptions: [--enable-enum]
- polymer:
    entry_points: example/index.html
